import type { EventItem } from "@/lib/database.types"

// DB boşsa / yapılandırılmamışsa /etkinlikler sayfası bu listeyi gösterir.
// DB seed'i (supabase/content.sql) ile aynı içerik.
export const EVENTS_FALLBACK: EventItem[] = [
  // — "Birlikte Derinleşiyoruz" ana sayfa etkinlikleri —
  {
    id: "fb-kokopellis",
    title: "Kokopellis Festivali",
    image_src: "/images/kokopellis.png",
    image_alt: "Kokopellis Festivali",
    date_label: "",
    location: "",
    event_type: "Festival",
    status: "past",
    description: "",
    capacity: "",
    is_featured: true,
    is_active: true,
    sort_order: 0,
    created_at: "",
  },
  {
    id: "fb-masal",
    title: "Masal Festivali",
    image_src: "/images/masal-festivali.png",
    image_alt: "Masal Festivali",
    date_label: "",
    location: "",
    event_type: "Festival",
    status: "past",
    description: "",
    capacity: "",
    is_featured: false,
    is_active: true,
    sort_order: 1,
    created_at: "",
  },
  {
    id: "fb-namaste",
    title: "Namaste Festivali",
    image_src: "/images/namaste-festivali.png",
    image_alt: "Namaste Festivali",
    date_label: "",
    location: "",
    event_type: "Festival",
    status: "past",
    description: "",
    capacity: "",
    is_featured: false,
    is_active: true,
    sort_order: 2,
    created_at: "",
  },
  {
    id: "fb-beyou",
    title: "Be Your Retreat",
    image_src: "/images/beyouretreat.png",
    image_alt: "Be Your Retreat",
    date_label: "",
    location: "",
    event_type: "Retreat",
    status: "past",
    description: "",
    capacity: "",
    is_featured: false,
    is_active: true,
    sort_order: 3,
    created_at: "",
  },
  // — Diğer geçmiş etkinlikler —
  {
    id: "fb-4",
    title: "Yogarama Yoga Festivali",
    image_src: "",
    image_alt: "",
    date_label: "18 - 22 Ekim 2023",
    location: "Grand Aygün Hotel, Çıralı",
    event_type: "Yoga, Mindfulness, Qigong, Müzik",
    status: "past",
    description:
      "Yoga, mindfulness, qigong, hang drum, satsang ve Yanartaş gezisi gibi içeriklerle düzenlenmiş kapsamlı bir yoga festivali.",
    capacity: "",
    is_featured: false,
    is_active: true,
    sort_order: 4,
    created_at: "",
  },
  {
    id: "fb-5",
    title: "Harmoniac Festival – Çıralı Edition",
    image_src: "",
    image_alt: "",
    date_label: "24 - 26 Nisan 2026",
    location: "Çıralı, Antalya",
    event_type: "Müzik, Yoga, Sound Healing, Breathwork",
    status: "past",
    description:
      "Yoga, nefes, ses şifası, müzik, aquatic bodywork ve Yanartaş atmosferiyle düzenlenen çok disiplinli wellness festivali.",
    capacity: "",
    is_featured: false,
    is_active: true,
    sort_order: 5,
    created_at: "",
  },
  {
    id: "fb-6",
    title: "Çıralı Nature Fest",
    image_src: "",
    image_alt: "",
    date_label: "12 Nisan 2025",
    location: "Yanartaş - Çıralı Sahili",
    event_type: "Doğa Yürüyüşü, Outdoor Etkinlik",
    status: "past",
    description:
      "Yanartaş'tan Çıralı sahiline uzanan doğa yürüyüşüyle turizm sezonunu açan bölgesel doğa etkinliği.",
    capacity: "",
    is_featured: false,
    is_active: true,
    sort_order: 6,
    created_at: "",
  },
]
